version: "3.9"
services:
  backend:
    build: ./src/backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./src/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
